### ISSUE TITLE
Inconsistent Sample entropy for same m when running for different m ranges

### ISSUE THREAD

**Issue by gunjanthesystem** [tjrantal/javaMSE#1]
Hi,

Thanks for your implementation.  Kindly clear my doubts or issue if it is.

I am observing that, for a given r (tolerance) and scale factor and for a particular m value,  **the sample entropy is different for different ranges of m_min to m_max**.

For example:
for a given sequence of numbers (https://goo.gl/mpqvY2), and r = 0.00001

![image](https://cloud.githubusercontent.com/assets/729448/8800454/c0d8abcc-2faa-11e5-83e8-54d4f5413d91.png)

As you can see from the table above, if I use m range as 1 to 5, then the value at m =2 is 0.7677 while if I use m range as 1 to 20 then the value at m =2 is 0.7540.  Kindly let me know if that is to be expected because **as far as I understand this should not be the case**.

(ps: Costa's C implementation also has the same issue/doubt)

Thanks

**Comment by tjrantal** [comment]
Thank you for the comment. I hadn't actually done such an experiment, so was surprised by your finding as well.

This certainly looks like unexpected and undesired behaviour, and this is caused by the implementation of sample entropy calculation. As you can confirm from the implementation of sample entropy calculation (lines 154-181 in edu/deakin/timo/MultiscaleEntropy.java), the data is only considered up to array length-m_max. If m_max is higher, more data points at the end of the array will be disregarded, and consequently there will be small differences in the SampEn depending on m_max. 

This could be rectified, by including the disregarded lower m values, and taking this into account when calculating the se values. However, I don't want to change this, because this is a port of Costa's code, and they have chosen to go with this implementation. There are quite a few publications out using MSE. Sadly details of the implementation aren't often included, so it is impossible to tell whether or not it would be a good idea to change the implementation. That is, to be comparable to existing literature, it would be good to use the same implementation.
